name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build & Push Frontend
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t bhaveshp14/fullstack-frontend:latest ./frontend --push

      - name: Build & Push Backend
        run: |
          docker buildx build --platform linux/amd64 \
            -t bhaveshp14/fullstack-backend:latest ./backend --push

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/fullstack-devops-app
            docker-compose pull
            docker-compose down
            docker-compose up -d
